name: main
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/resuse.yaml
    with:
      docker-args: |
        ENV1=${{ env.TEST1 }}
        ENV2=${{ env.TEST2 }}
