name: os-env
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/resuse.yaml
    with:
      docker-args: '[{"name": "TEST1", "value": "${TEST1}"},{"name": "TEST2", "value": "${TEST2}"}]'
